### ISSUE TITLE
Primary Menu Layouts Conflict in Customizer in mobile view

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#21] opened 2019-03-28 07:35 UTC
as mentioned earlier for bug 2(mentioned below)
https://github.com/genesisplugins/genesis-customizer/issues/12

Header > Primary Header.

**1.** Desktop Layout 5 sometime not works in Customizer. 
![image](https://user-images.githubusercontent.com/34836534/55138629-ee17ff00-5159-11e9-9a56-9f6e839a35b3.png)

**2.** Mobile toggle also not  show secondary navigation when Mobile layout change in Customizer. 
This bug is also not working on after exit from Customizer or view in incognito mode. https://github.com/genesisplugins/genesis-customizer/issues/12

**3.** Site header (title-area) hides when resized, when Desktop Layout 2 is used. Menu toggle behaviour depends on user is logged or not.
![image](https://user-images.githubusercontent.com/34836534/55138669-0ab43700-515a-11e9-9b67-e08ade98e078.png)

**Comment by rockingaryan** [comment] 2019-03-28 07:40
All the layout types for Primary Header are currently free. Desktop layout like 2 and 5 should be a pro feature.

**Comment by rockingaryan** [comment] 2019-03-28 07:41
2nd layout for desktop need also this fix https://github.com/genesisplugins/genesis-customizer/issues/8

**Comment by rockingaryan** [comment] 2019-03-28 14:08
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment] 2019-03-29 04:42
- [x] Side header layout
- [x] Secondary menu not moving into responsive menu
- [ ] Title area hiding ?

**Comment by genesisplugins** [comment] 2019-03-29 04:43
@rockingaryan is the third issue still happening? I'm not able to reproduce.

**Comment by rockingaryan** [comment] 2019-03-29 05:27
I think this only float for the first time when resizing in mobile view. This should be marked as fixed for now.

**Comment by genesisplugins** [comment] 2019-03-31 12:02
Fixed in ee29849

**Closed by genesisplugins** 2019-03-31 12:02 UTC
Labels: bug, enhancement
